# Generated by Django 3.2.16 on 2022-12-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_rename_username_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created',
            new_name='timestamp',
        ),
    ]
